me: Ignat Harczuk
markdown: redcarpet
pygments: true
github: https://www.github.com/fishstamp82
about: I am a theoretical chemist that enjoys all sorts of programming from studying basic datastructure to web-development.
urls:
    - text: github
      url: https://github.com/fishstamp82
    - text: mailto
      url: mailto:ignathe@gmail.com
